version: '3.8'

services:
  messagebus:
    image: rabbitmq:latest
    container_name: messagebus
    hostname: "messagebus"
    labels:
        NAME: "messagebus"
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"
    
  mydatabase:
    image: mongo:latest
    container_name: mydatabase
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
    #   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - week4network
    ports:
      - "27017:27017"

  myapi:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=${MONGO_URL}/${DB_NAME}
    volumes:
      - ./api:/app
    networks:
      - week4network
    container_name: myapi
    depends_on:
      - mydatabase
      
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:80"
  #   environment:
  #     - API_URL=${API_URL}
  #   networks:
  #     - week4network
  #   container_name: frontend
  
  grafana:
    build: ./Services/Grafana
    container_name: grafana
    ports:
      - '${GRAFANA_PORT:-5000}:3000'
    networks:
      - week4network
    restart: unless-stopped
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./Services/Prometheus:/etc/prometheus
      - ./data/prometheus:/prometheus
    ports:
      - '${PROM_PORT:-9090}:9090'
    networks:
      - week4network
    command: --web.enable-lifecycle --config.file=/etc/prometheus/config.yml
    restart: unless-stopped
    depends_on:
      - myapi
      - mongodb-exporter

  mongodb-exporter:
    image: bitnami/mongodb-exporter:latest
    ports:
      - "9216:9216"
    environment:
      - MONGODB_URI=mongodb://mydatabase:27017
    networks:
      - week4network
    container_name: mongodb-exporter
    depends_on:
      - mydatabase

# Define named volumes
volumes:
  mongo_data:
  prometheus-data:

# Define custom network
networks:
  week4network:
    driver: bridge
