version: '3.8'

services:
  messagebus:
    image: rabbitmq:latest
    container_name: messagebus
    ports:
      - '${BROKER_HTTP_PORT:-15672}:15672'
    restart: unless-stopped
    
  mydatabase:
    image: mongo:latest
    container_name: mydatabase
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME:-week4username}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD:-week4password}
    volumes:
      - mongo_data:/data/db
      # - ./data/db:/data/db
    networks:
      - week4network
    ports:
      - "27017:27017"

  myapi:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '${APP_PORT:-8000}:3000'
    env_file:
      - .env
    environment:
      # MONGO_URL: ${MONGO_URL}/${DB_NAME}
      JWT_SECRET: '${JWT_SECRET}'
      TARGET_SERVICE_URL: 'http://target-service:${TARGET_SERVICE_PORT:-4000}'
      USER_SERVICE_URL: 'http://service-user:${USER_SERVICE_PORT:-3000}'
    volumes:
      - ./api:/app
    networks:
      - week4network
    container_name: myapi
    depends_on:
      - mydatabase
      - user-service
      - target-service

  attempt-service:
    image: node:20.11.1
    container_name: 'service-attempt'
    working_dir: /var/www/html
    volumes:
      - ./Services/AttemptService:/var/www/html
    networks:
      - week4network
    environment:
      APP_PORT: '${ATTEMPT_SERVICE_PORT:-3000}'
      DB_URL: 'mongodb://mydatabase:27017/attempts'
      DB_USERNAME: '${DB_USERNAME:-week4username}'
      DB_PASSWORD: '${DB_PASSWORD:-week4password}'
    command: bash -c "npm install && npm run watch"
    # restart: unless-stopped
    depends_on:
      - messagebus
      - mydatabase

  user-service:
    image: node:20.11.1
    container_name: 'service-user'
    working_dir: /var/www/html
    volumes:
      - ./Services/UserService:/var/www/html
    networks:
      - week4network
    environment:
      APP_PORT: '${USER_SERVICE_PORT:-3000}'
      DB_URL: 'mongodb://mydatabase:27017/users'
      DB_USERNAME: '${DB_USERNAME:-week4username}'
      DB_PASSWORD: '${DB_PASSWORD:-week4password}'
    command: bash -c "npm install && npm run watch"
    # restart: unless-stopped
    depends_on:
      - messagebus
      - mydatabase
      
  target-service:
    image: node:20.11.1
    container_name: 'service-target'
    working_dir: /var/www/html
    volumes:
      - ./Services/TargetService:/var/www/html
    networks:
      - week4network
    environment:
      APP_PORT: '${TARGET_SERVICE_PORT:-4000}'
      USER_SERVICE_URL: 'http://service-user:${USER_SERVICE_PORT:-3000}'
      TARGET_SERVICE_URL: 'http://service-target:${TARGET_SERVICE_PORT:-4000}'
      DB_URL: 'mongodb://mydatabase:27017/targets'
      DB_USERNAME: '${DB_USERNAME:-week4username}'
      DB_PASSWORD: '${DB_PASSWORD:-week4password}'
    command: bash -c "npm install && npm run watch"
    depends_on:
      - messagebus
      - mydatabase
    restart: unless-stopped

  # Monitoring services
  grafana:
    build: ./Services/Grafana
    container_name: grafana
    ports:
      - '${GRAFANA_PORT:-5000}:3000'
    networks:
      - week4network
    restart: unless-stopped
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./Services/Prometheus:/etc/prometheus
      - ./data/prometheus:/prometheus
    ports:
      - '${PROM_PORT:-9090}:9090'
    networks:
      - week4network
    command: --web.enable-lifecycle --config.file=/etc/prometheus/config.yml
    restart: unless-stopped
    depends_on:
      - myapi
      - mongodb-exporter

  alert-manager:
    container_name: service-alert
    image: quay.io/prometheus/alertmanager
    restart: unless-stopped
    volumes:
      - ./Services/AlertService:/etc/prometheus
    command: --config.file=/etc/prometheus/alertmanager.yml
    networks:
      - week4network

  mongodb-exporter:
    image: bitnami/mongodb-exporter:latest
    ports:
      - "9216:9216"
    environment:
      MONGODB_URI: 'mongodb://${DB_USERNAME:-week4username}:${DB_PASSWORD:-week4password}@mydatabase:27017'
    networks:
      - week4network
    container_name: mongodb-exporter
    depends_on:
      - mydatabase

  # Mail service
  mailhog:
    container_name: service-mail
    image: mailhog/mailhog:latest
    restart: unless-stopped
    ports:
      - '${MAILHOG_PORT:-8004}:8025'
      - '1025:1025'
    networks:
      - week4network

# Define named volumes
volumes:
  mongo_data:
  prometheus-data:

# Define custom network
networks:
  week4network:
    driver: bridge
