name: API Tests and Coverage

on:
  push:
    paths:
      - 'api/**'
  pull_request:
    branches:
      - main

jobs:
  test_and_coverage:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install dependencies and run tests
        run: |
          cd api
          npm install
          npm test
          npm run lint

      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2.3.0
        with:
          files: './api/coverage/**/lcov.info'
