name: API Tests and Coverage

on:
  push:
    paths:
      - 'api/**'
  pull_request:
    branches:
      - main

jobs:
  test_and_coverage:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test
        working-directory: ./api

      - name: Generate Coverage Report
        run: npm run coverage
        working-directory: ./api

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ./api/coverage

      - name: Check Code Coverage
        run: |
          threshold=$(node -p "(${{ github.event_name == 'push' }} && 90) || (${{ github.event_name == 'pull_request' }} && 80)")
          actual=$(node -p "require('./api/coverage/coverage-summary.json').total.lines.pct")
          if (( $(echo "$actual < $threshold" | bc -l) )); then
            echo "Code coverage below threshold. Current coverage: $actual, Threshold: $threshold"
            exit 1
          else
            echo "Code coverage meets threshold: $actual"
          fi
